# ruff: noqa
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import base64
import datetime
import json
import os
from zoneinfo import ZoneInfo

from a2ui.basic_catalog.provider import BasicCatalog
from a2ui.schema.manager import A2uiSchemaManager
from google import genai
from google.adk.agents import Agent
from google.adk.agents.callback_context import CallbackContext
from google.adk.apps import App
from google.adk.code_executors import AgentEngineSandboxCodeExecutor
from google.adk.models import Gemini
from google.adk.tools import ToolContext
from google.adk.tools.preload_memory_tool import PreloadMemoryTool
from google.cloud import firestore, storage
from google.genai import types
import requests

from app.a2ui_utils import a2ui_callback

# CRITICAL: Hardcode project ID and GCS bucket name as strings
FIRESTORE_PROJECT = "qwiklabs-gcp-02-aad533fba737"
GCS_BUCKET_NAME = "smart-pantry-recipes-qwiklabs-gcp-02-aad533fba737"

# Load Agent Engine resource name from deployment_metadata.json if present
DEPLOYMENT_METADATA_PATH = os.path.join(os.path.dirname(__file__), "..", "deployment_metadata.json")
REMOTE_AGENT_RUNTIME_ID = "projects/934830090635/locations/us-east1/reasoningEngines/6858764529182965760"

if os.path.exists(DEPLOYMENT_METADATA_PATH):
    try:
        with open(DEPLOYMENT_METADATA_PATH) as f:
            meta = json.load(f)
            REMOTE_AGENT_RUNTIME_ID = meta.get("remote_agent_runtime_id", REMOTE_AGENT_RUNTIME_ID)
    except Exception:
        pass

code_executor = AgentEngineSandboxCodeExecutor(
    agent_engine_resource_name=REMOTE_AGENT_RUNTIME_ID
)


async def generate_memories_callback(callback_context: CallbackContext):
    """WRITE: after each turn, send session events to Vertex AI Memory Bank for extraction."""
    try:
        await callback_context.add_session_to_memory()
    except ValueError as e:
        if "memory service is not available" in str(e):
            from app.app_utils.services import get_memory_service
            memory_service = get_memory_service()
            if memory_service and callback_context._invocation_context.session:
                await memory_service.add_session_to_memory(callback_context._invocation_context.session)
        else:
            raise e
    except Exception:
        pass
    return None


def generate_recipe_image(prompt: str, tool_context: ToolContext) -> str:
    """Generates an image for a recipe or dish using the gemini-3.1-flash-lite-image model in global region,
    saves it as an ADK artifact, and uploads the image bytes directly to a public Cloud Storage bucket.

    Args:
        prompt: Detailed prompt describing the food image to generate (e.g. 'Avocado sourdough toast with poached egg').
        tool_context: ADK ToolContext injected automatically for saving artifacts.

    Returns:
        Confirmation message with the public GCS URL of the generated image.
    """
    client = genai.Client(vertexai=True, project=FIRESTORE_PROJECT, location="global")
    response = client.models.generate_content(
        model="gemini-3.1-flash-lite-image",
        contents=prompt,
        config=types.GenerateContentConfig(response_modalities=["IMAGE"]),
    )

    image_bytes = None
    mime_type = "image/jpeg"

    if response.candidates:
        for candidate in response.candidates:
            if candidate.content and candidate.content.parts:
                for part in candidate.content.parts:
                    if part.inline_data:
                        image_bytes = part.inline_data.data
                        if part.inline_data.mime_type:
                            mime_type = part.inline_data.mime_type
                        break
            if image_bytes:
                break

    if not image_bytes:
        return "Error: No image bytes were generated by the model."

    timestamp = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
    filename = f"recipe_{timestamp}.jpg"

    # (1) Save with tool_context.save_artifact for Playground Artifacts panel
    artifact_part = types.Part.from_bytes(data=image_bytes, mime_type=mime_type)
    tool_context.save_artifact(filename=filename, artifact=artifact_part)

    # (2) Upload image bytes directly to public GCS bucket (no local file writing)
    storage_client = storage.Client(project=FIRESTORE_PROJECT)
    bucket = storage_client.bucket(GCS_BUCKET_NAME)
    blob = bucket.blob(filename)
    blob.upload_from_string(image_bytes, content_type=mime_type)

    public_url = f"https://storage.googleapis.com/{GCS_BUCKET_NAME}/{filename}"
    return f"Image generated successfully!\nPublic GCS URL: {public_url}"


def generate_recipe_video(prompt: str, tool_context: ToolContext) -> str:
    """Generates a short video for a food item or recipe in the agent's domain using Google's Omni model (gemini-omni-flash-preview) in global region,
    saves it as an ADK artifact, and uploads the video bytes directly to a public Cloud Storage bucket.

    Args:
        prompt: Detailed prompt describing the food item or recipe video to generate (e.g. 'A short video of a sizzling steak with garlic and rosemary').
        tool_context: ADK ToolContext injected automatically for saving artifacts.

    Returns:
        Public HTTPS URL of the generated video stored in Cloud Storage.
    """
    client = genai.Client(vertexai=True, project=FIRESTORE_PROJECT, location="global")
    response = client.interactions.create(
        model="gemini-omni-flash-preview",
        input=prompt,
        generation_config={"response_modalities": ["TEXT", "VIDEO"]},
    )

    video_bytes = None
    mime_type = "video/mp4"

    if hasattr(response, "output_video") and response.output_video:
        data = getattr(response.output_video, "data", None)
        if data:
            if isinstance(data, str):
                video_bytes = base64.b64decode(data)
            elif isinstance(data, bytes):
                video_bytes = data
            if hasattr(response.output_video, "mime_type") and response.output_video.mime_type:
                mime_type = response.output_video.mime_type

    if not video_bytes:
        return "Error: No video bytes were generated by the Omni model."

    timestamp = int(datetime.datetime.now(datetime.timezone.utc).timestamp())
    filename = f"recipe_video_{timestamp}.mp4"

    # (1) Save with tool_context.save_artifact so it shows up in Playground's Artifacts panel
    artifact_part = types.Part.from_bytes(data=video_bytes, mime_type=mime_type)
    tool_context.save_artifact(filename=filename, artifact=artifact_part)

    # (2) Upload video bytes directly to public GCS bucket (no local file writing)
    storage_client = storage.Client(project=FIRESTORE_PROJECT)
    bucket = storage_client.bucket(GCS_BUCKET_NAME)
    blob = bucket.blob(filename)
    blob.upload_from_string(video_bytes, content_type=mime_type)

    public_url = f"https://storage.googleapis.com/{GCS_BUCKET_NAME}/{filename}"
    return public_url


def geocode_address(address: str) -> str:
    """Converts a street address or city name into geographic coordinates (latitude and longitude) using Google Geocoding API.

    Args:
        address: The address or place name to geocode (e.g. '1600 Amphitheatre Pkwy, Mountain View, CA' or 'San Francisco, CA').

    Returns:
        String with formatted address and latitude/longitude coordinates.
    """
    api_key = os.getenv("GOOGLE_MAPS_API_KEY")
    if not api_key:
        return "Error: GOOGLE_MAPS_API_KEY environment variable is not configured."

    url = f"https://maps.googleapis.com/maps/api/geocode/json?address={requests.utils.quote(address)}&key={api_key}"

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()

        results = data.get("results")
        if not results:
            return f"No location coordinates found for address: '{address}'."

        first = results[0]
        formatted_address = first.get("formatted_address", address)
        loc = first.get("geometry", {}).get("location", {})
        lat, lng = loc.get("lat"), loc.get("lng")

        return f"Address: {formatted_address}\nLocation Coordinates: Latitude {lat}, Longitude {lng}"
    except Exception as e:
        return f"Error geocoding address: {str(e)}"


def find_nearby_places(latitude: float, longitude: float, place_type: str = "supermarket", radius_meters: float = 2000.0) -> str:
    """Finds nearby places (e.g., supermarkets, grocery stores, bakeries) near given coordinates using Places API (New).

    Args:
        latitude: Center latitude coordinate.
        longitude: Center longitude coordinate.
        place_type: Type of place to search for (e.g. 'supermarket', 'grocery_store', 'bakery', 'restaurant').
        radius_meters: Search radius in meters (default 2000 meters / ~1.2 miles).

    Returns:
        Formatted summary of nearby places with name, address, and location coordinates.
    """
    api_key = os.getenv("GOOGLE_MAPS_API_KEY")
    if not api_key:
        return "Error: GOOGLE_MAPS_API_KEY environment variable is not configured."

    url = "https://places.googleapis.com/v1/places:searchNearby"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": api_key,
        "X-Goog-FieldMask": "places.displayName,places.formattedAddress,places.location",
    }
    payload = {
        "includedTypes": [place_type],
        "locationRestriction": {
            "circle": {
                "center": {
                    "latitude": latitude,
                    "longitude": longitude,
                },
                "radius": radius_meters,
            }
        },
    }

    try:
        response = requests.post(url, json=payload, headers=headers, timeout=10)
        response.raise_for_status()
        data = response.json()

        places = data.get("places", [])
        if not places:
            return f"No nearby places of type '{place_type}' found within {radius_meters}m of ({latitude}, {longitude})."

        results = []
        for p in places[:5]:  # Top 5 places
            display_name = p.get("displayName", {}).get("text", "Unknown Place")
            formatted_address = p.get("formattedAddress", "N/A")
            loc = p.get("location", {})
            p_lat, p_lng = loc.get("latitude"), loc.get("longitude")

            results.append(
                f"- Name: {display_name}\n"
                f"  Address: {formatted_address}\n"
                f"  Location: Latitude {p_lat}, Longitude {p_lng}"
            )

        return f"Found {len(results)} nearby '{place_type}' place(s):\n\n" + "\n\n".join(results)
    except Exception as e:
        return f"Error finding nearby places: {str(e)}"


def lookup_global_recipes(query: str) -> str:
    """Fetches real external recipes from TheMealDB public global recipe API.

    Args:
        query: Recipe or dish name to search for (e.g., 'pasta', 'chicken', 'tacos').

    Returns:
        Formatted summary of global recipes matching the query.
    """
    api_key = os.getenv("MEALDB_API_KEY", "1")
    url = f"https://www.themealdb.com/api/json/v1/{api_key}/search.php?s={query.strip()}"

    try:
        response = requests.get(url, timeout=10)
        response.raise_for_status()
        data = response.json()
        meals = data.get("meals")

        if not meals:
            return f"No global recipes found for '{query}'."

        results = []
        for meal in meals[:3]:  # Top 3 results
            name = meal.get("strMeal", "Unknown")
            category = meal.get("strCategory", "General")
            area = meal.get("strArea", "International")
            instructions = meal.get("strInstructions", "No instructions provided.").replace("\r\n", " ")
            if len(instructions) > 200:
                instructions = instructions[:197] + "..."

            results.append(
                f"- Name: {name} ({area} {category})\n"
                f"  Instructions: {instructions}\n"
                f"  Image: {meal.get('strMealThumb', 'N/A')}"
            )

        return f"Found {len(results)} global recipe(s) for '{query}':\n\n" + "\n\n".join(results)
    except Exception as e:
        return f"Error fetching global recipes: {str(e)}"


def search_recipes(query: str = "") -> str:
    """Searches the Firestore database for recipes matching a query by name, category, or ingredient.

    Args:
        query: Search term for recipe name, category (e.g., Breakfast, Lunch, Dinner), or ingredient.

    Returns:
        A string summarizing the matching recipes found in Firestore.
    """
    db = firestore.Client(project=FIRESTORE_PROJECT)
    docs = db.collection("recipes").stream()

    matches = []
    q = query.lower().strip()

    for doc in docs:
        data = doc.to_dict()
        name = data.get("name", "")
        category = data.get("category", "")
        ingredients = data.get("ingredients", [])

        if not q or q in name.lower() or q in category.lower() or any(q in ing.lower() for ing in ingredients):
            matches.append(
                f"- ID: {doc.id} | Name: {name} | Category: {category} | Prep: {data.get('prep_time_minutes')}m\n"
                f"  Ingredients: {', '.join(ingredients)}\n"
                f"  Instructions: {data.get('instructions')}"
            )

    if not matches:
        return f"No recipes found matching '{query}' in the database."

    return f"Found {len(matches)} recipe(s):\n\n" + "\n\n".join(matches)


def add_recipe(recipe_id: str, name: str, category: str, prep_time_minutes: int, ingredients: list[str], instructions: str) -> str:
    """Adds a new recipe or updates an existing recipe in the Firestore database.

    Args:
        recipe_id: Unique ID for the recipe (e.g., 'recipe-004').
        name: Name of the dish.
        category: Dish category (e.g. 'Breakfast', 'Lunch', 'Dinner', 'Dessert').
        prep_time_minutes: Total preparation time in minutes.
        ingredients: List of ingredient strings.
        instructions: Preparation instructions.

    Returns:
        Confirmation message that the recipe was saved to Firestore.
    """
    db = firestore.Client(project=FIRESTORE_PROJECT)
    doc_ref = db.collection("recipes").document(recipe_id)
    recipe_data = {
        "id": recipe_id,
        "name": name,
        "category": category,
        "prep_time_minutes": prep_time_minutes,
        "ingredients": ingredients,
        "instructions": instructions,
    }
    doc_ref.set(recipe_data)
    return f"Successfully saved recipe '{name}' (ID: {recipe_id}) to Firestore."


def add_to_grocery_list(items: list[str]) -> str:
    """Adds items to the user's grocery shopping list in Firestore.

    Args:
        items: List of ingredient or grocery item names to add (e.g. ["1 ripe avocado", "2 sourdough slices"]).

    Returns:
        Confirmation message listing the items added.
    """
    db = firestore.Client(project=FIRESTORE_PROJECT)
    collection_ref = db.collection("grocery_list")

    added = []
    for item in items:
        item_name = item.strip()
        if item_name:
            doc_ref = collection_ref.document()
            doc_ref.set({
                "item": item_name,
                "added_at": datetime.datetime.now(datetime.timezone.utc).isoformat()
            })
            added.append(item_name)

    return f"Added {len(added)} item(s) to your grocery list: {', '.join(added)}."


def get_grocery_list() -> str:
    """Retrieves all current items from the user's grocery shopping list in Firestore.

    Returns:
        Formatted string listing all items on the grocery list.
    """
    db = firestore.Client(project=FIRESTORE_PROJECT)
    docs = db.collection("grocery_list").stream()

    items = [doc.to_dict().get("item", "") for doc in docs if doc.to_dict().get("item")]
    if not items:
        return "Your grocery list is currently empty."

    formatted = "\n".join([f"- {item}" for item in items])
    return f"Your Grocery List ({len(items)} items):\n{formatted}"


def get_weather(query: str) -> str:
    """Simulates a web search. Use it get information on weather.

    Args:
        query: A string containing the location to get weather information for.

    Returns:
        A string with the simulated weather information for the queried location.
    """
    if "sf" in query.lower() or "san francisco" in query.lower():
        return "It's 60 degrees and foggy."
    return "It's 90 degrees and sunny."


def get_current_time(query: str) -> str:
    """Simulates getting the current time for a city.

    Args:
        query: The name of the city to get the current time for.

    Returns:
        A string with the current time information.
    """
    if "sf" in query.lower() or "san francisco" in query.lower():
        tz_identifier = "America/Los_Angeles"
    else:
        return f"Sorry, I don't have timezone information for query: {query}."

    tz = ZoneInfo(tz_identifier)
    now = datetime.datetime.now(tz)
    return f"The current time for query {query} is {now.strftime('%Y-%m-%d %H:%M:%S %Z%z')}"


# --- A2UI Setup (v0.8) ---
schema_manager = A2uiSchemaManager(
    version="0.8",
    catalogs=[BasicCatalog.get_config("0.8")],
)

a2ui_instruction = schema_manager.generate_system_prompt(
    role_description="You are a Smart Pantry & Recipe Concierge. Help users discover recipes, generate dish images, execute Python calculations safely, find nearby supermarkets, manage recipe data, and maintain their grocery list.",
    workflow_description="Analyze the request and return structured A2UI visual cards when appropriate.",
    ui_description=(
        "MEMORY & ALLERGY RULES:\n"
        "- Pay strict attention to all user-stated food allergies (e.g., peanuts, gluten, dairy, shellfish, nuts, eggs, soy), dietary restrictions, and personal preferences.\n"
        "- Always remember and recall any allergies stated in past or current conversations.\n"
        "- NEVER suggest recipes or add grocery items that contain ingredients the user is allergic to.\n\n"
        "A2UI DESIGN RULES:\n"
        "Keep every surface tiny and flat: ONE Card > ONE Column > a few Text rows. "
        "Never nest a Card inside a Card. "
        "Use ONLY these components: Card, Column, Row, Text, and Image. Do not use "
        "Table or Heading (unsupported), or Buttons, actions, or forms (they do "
        "nothing in adk web). "
        "You may include one Image component, but only when you have a public https "
        "URL for the image (for example the URL an image tool returns after uploading "
        "to a public bucket). Set the Image url to that exact https link, for example "
        "{\"Image\": {\"url\": {\"literalString\": \"https://...\"}}}. Never point an "
        "Image at a bare filename, an artifact name, or a non-http(s) path. If you do "
        "not have a public URL, add a short Text line noting the image instead. "
        "No markdown in text; use the usageHint property ('h1', 'h2', 'body') for "
        "headings and emphasis. "
        "Output ONLY the raw A2UI JSON array — no prose, and never wrap it in "
        "<a2a_datapart_json> tags or 'kind'/'data'/'metadata' objects."
    ),
    include_schema=True,
    include_examples=True,
)


root_agent = Agent(
    name="root_agent",
    model=Gemini(
        model="gemini-2.5-flash",
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=a2ui_instruction,
    code_executor=code_executor,
    tools=[
        PreloadMemoryTool(),
        generate_recipe_image,
        generate_recipe_video,
        geocode_address,
        find_nearby_places,
        lookup_global_recipes,
        search_recipes,
        add_recipe,
        add_to_grocery_list,
        get_grocery_list,
        get_weather,
        get_current_time,
    ],
    after_agent_callback=generate_memories_callback,
    after_model_callback=a2ui_callback,
)

app = App(
    root_agent=root_agent,
    name="app",
)
